import type { Metadata } from "next";
import "./globals.css";
import { Navbar} from "@/Components";
import { raleway } from "./fonts";

export const metadata: Metadata = {
  title: "African Plains Conservation Trust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
